# Generated by Django 4.2.6 on 2023-10-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       sectors',
                'db_table': 'sectors',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='scraper_pipes.sector')),
            ],
            options={
                'verbose_name_plural': '       stocks',
                'db_table': 'stocks',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='StockBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('bid_vol', models.FloatField(blank=True, null=True)),
                ('bid_price', models.FloatField(blank=True, null=True)),
                ('offer_vol', models.FloatField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='scraper_pipes.stock')),
            ],
            options={
                'verbose_name_plural': '       stocks_buffers',
                'db_table': 'stocks_buffers',
                'ordering': ['-captured_at'],
            },
        ),
    ]
