# Generated by Django 5.0 on 2023-12-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '       commodities',
                'db_table': 'commodities',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       stocks',
                'db_table': 'stocks',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CommodityBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment.commodity')),
            ],
            options={
                'verbose_name_plural': '       commodities_buffers',
                'db_table': 'commodities_buffers',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='StockBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('bid_vol', models.FloatField(blank=True, null=True)),
                ('bid_price', models.FloatField(blank=True, null=True)),
                ('offer_vol', models.FloatField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment.stock')),
            ],
            options={
                'verbose_name_plural': '       stocks_buffers',
                'db_table': 'stocks_buffers',
                'ordering': ['-captured_at'],
            },
        ),
    ]
