# Generated by Django 5.0 on 2023-12-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
