# Generated by Django 5.0 on 2023-12-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='symbol',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
