# Generated by Django 5.0 on 2023-12-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='symbol',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
