# Generated by Django 5.0 on 2023-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_commodity_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbuffer',
            name='close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbuffer',
            name='high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbuffer',
            name='low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbuffer',
            name='open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
