# Generated by Django 5.0 on 2024-01-09 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_stockbuffer_close_stockbuffer_high_stockbuffer_low_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('symbol', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': '       Cryptos',
                'db_table': 'cryptos',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='CryptoBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('close', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment.crypto')),
            ],
            options={
                'verbose_name_plural': '       cryptos_buffers',
                'db_table': 'cryptos_buffers',
                'ordering': ['-captured_at'],
            },
        ),
    ]
