# Generated by Django 5.0 on 2024-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0006_crypto_cryptobuffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptobuffer',
            name='bid_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptobuffer',
            name='bid_vol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptobuffer',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptobuffer',
            name='offer_vol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
