# Generated by Django 4.2.6 on 2023-10-14 09:53

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import general_funcs.storage_func


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environment_simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(max_length=255, unique=True, verbose_name='user name')),
                ('user_string', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=general_funcs.storage_func.OverwriteStorage(), upload_to='profile_images')),
                ('base64Image', models.TextField(blank=True, null=True)),
                ('imageType', models.CharField(blank=True, max_length=10, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('digi6Code', models.CharField(blank=True, max_length=6, null=True)),
                ('is6Code_verified', models.BooleanField(default=False)),
                ('simulated_portfolio_value', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       Traders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='environment_simulator.simulatedstock')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '       simulated_ownerships',
                'db_table': 'simulated_ownerships',
                'ordering': ['-shares'],
            },
        ),
    ]
