# Generated by Django 4.2.5 on 2023-10-07 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment_simulator', '0006_simulatedstockbuffer_bid_price_and_more'),
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='simulated_portfolio_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SimulatedOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='environment_simulator.simulatedstock')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '       simulated_ownerships',
                'db_table': 'simulated_ownerships',
                'ordering': ['-shares'],
            },
        ),
    ]
