# Generated by Django 5.0 on 2023-12-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('gradient', models.FloatField(blank=True, null=True)),
                ('sd', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('avg_forward_steps', models.IntegerField(blank=True, null=True)),
                ('avg_backward_steps', models.IntegerField(blank=True, null=True)),
                ('steps_left', models.IntegerField(blank=True, null=True)),
                ('units', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '       simulated_commodities',
                'db_table': 'simulated_commodities',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       simulated_sectors',
                'db_table': 'simulated_sectors',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedCommodityBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment_simulator.simulatedcommodity')),
            ],
            options={
                'verbose_name_plural': '       simulated_commodities_buffers',
                'db_table': 'simulated_commodities_buffers',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedCommodityCovariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(blank=True, null=True)),
                ('commodity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_b_covariances', to='environment_simulator.simulatedcommodity')),
                ('commodity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_a_covariances', to='environment_simulator.simulatedcommodity')),
            ],
            options={
                'verbose_name_plural': '       simulated_commodities_covariances',
                'db_table': 'simulated_commodities_covariances',
            },
        ),
        migrations.CreateModel(
            name='SimulatedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('price_gradient', models.FloatField(blank=True, null=True)),
                ('price_sd', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('avg_forward_steps', models.IntegerField(blank=True, null=True)),
                ('avg_backward_steps', models.IntegerField(blank=True, null=True)),
                ('price_steps_left', models.IntegerField(blank=True, null=True)),
                ('volume_sd', models.FloatField(blank=True, null=True)),
                ('price_x_volume_factor', models.FloatField(blank=True, null=True)),
                ('volume_x_price_factor', models.FloatField(blank=True, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='environment_simulator.simulatedsector')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks',
                'db_table': 'simulated_stocks',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedStockBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('bid_vol', models.FloatField(blank=True, null=True)),
                ('bid_price', models.FloatField(blank=True, null=True)),
                ('offer_vol', models.FloatField(blank=True, null=True)),
                ('offer_price', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment_simulator.simulatedstock')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks_buffers',
                'db_table': 'simulated_stocks_buffers',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedStockCovariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(blank=True, null=True)),
                ('stock_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_b_covariances', to='environment_simulator.simulatedstock')),
                ('stock_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_a_covariances', to='environment_simulator.simulatedstock')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks_covariances',
                'db_table': 'simulated_stocks_covariances',
            },
        ),
        migrations.CreateModel(
            name='SimulatedStockXCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_covariances', to='environment_simulator.simulatedcommodity')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_covariances', to='environment_simulator.simulatedstock')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks_x_commodities',
                'db_table': 'simulated_stocks_x_commodities',
            },
        ),
    ]
