# Generated by Django 4.2.5 on 2023-09-29 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment_simulator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '       simulated_sectors',
                'db_table': 'simulated_sectors',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('price_gradient', models.FloatField(blank=True, null=True)),
                ('price_sd', models.FloatField(blank=True, null=True)),
                ('min_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('avg_forward_steps', models.IntegerField(blank=True, null=True)),
                ('avg_backward_steps', models.IntegerField(blank=True, null=True)),
                ('price_steps_left', models.IntegerField(blank=True, null=True)),
                ('volume_sd', models.FloatField(blank=True, null=True)),
                ('volume_x_price_factor', models.FloatField(blank=True, null=True)),
                ('price_x_volume_factor', models.FloatField(blank=True, null=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='environment_simulator.simulatedsector')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks',
                'db_table': 'simulated_stocks',
                'ordering': ['index'],
            },
        ),
        migrations.RenameField(
            model_name='simulatedcommodity',
            old_name='steps_to_reversal',
            new_name='avg_backward_steps',
        ),
        migrations.RemoveField(
            model_name='simulatedcommodity',
            name='price',
        ),
        migrations.RemoveField(
            model_name='simulatedcommodity',
            name='tensor_weight',
        ),
        migrations.AddField(
            model_name='simulatedcommodity',
            name='avg_forward_steps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SimulatedStockCovariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(blank=True, null=True)),
                ('stock_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_b_covariances', to='environment_simulator.simulatedstock')),
                ('stock_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_a_covariances', to='environment_simulator.simulatedstock')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks_covariances',
                'db_table': 'simulated_stocks_covariances',
            },
        ),
        migrations.CreateModel(
            name='SimulatedStockBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('ldcp', models.FloatField(blank=True, null=True)),
                ('open', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment_simulator.simulatedstock')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks_buffers',
                'db_table': 'simulated_stocks_buffers',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='SimulatedCommodityCovariance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(blank=True, null=True)),
                ('commodity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_b_covariances', to='environment_simulator.simulatedcommodity')),
                ('commodity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_a_covariances', to='environment_simulator.simulatedcommodity')),
            ],
            options={
                'verbose_name_plural': '       simulated_commodities_covariances',
                'db_table': 'simulated_commodities_covariances',
            },
        ),
        migrations.CreateModel(
            name='SimulatedCommodityBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('price_snapshot', models.FloatField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_snapshots', to='environment_simulator.simulatedcommodity')),
            ],
            options={
                'verbose_name_plural': '       simulated_commodities_buffers',
                'db_table': 'simulated_commodities_buffers',
                'ordering': ['-captured_at'],
            },
        ),
    ]
