# Generated by Django 4.2.5 on 2023-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_simulator', '0002_simulatedsector_simulatedstock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedcommodity',
            name='units',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
