# Generated by Django 4.2.5 on 2023-10-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('environment_simulator', '0003_simulatedcommodity_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedStockXCommodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.FloatField(blank=True, null=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_covariances', to='environment_simulator.simulatedcommodity')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_covariances', to='environment_simulator.simulatedstock')),
            ],
            options={
                'verbose_name_plural': '       simulated_stocks_x_commodities',
                'db_table': 'simulated_stocks_x_commodities',
            },
        ),
    ]
