# Generated by Django 4.2.5 on 2023-10-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment_simulator', '0004_simulatedstockxcommodity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatedstockbuffer',
            name='high',
        ),
        migrations.RemoveField(
            model_name='simulatedstockbuffer',
            name='ldcp',
        ),
        migrations.RemoveField(
            model_name='simulatedstockbuffer',
            name='low',
        ),
        migrations.RemoveField(
            model_name='simulatedstockbuffer',
            name='open',
        ),
    ]
