# Generated by Django 4.2.5 on 2023-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_simulator', '0005_remove_simulatedstockbuffer_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedstockbuffer',
            name='bid_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulatedstockbuffer',
            name='bid_vol',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulatedstockbuffer',
            name='offer_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulatedstockbuffer',
            name='offer_vol',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
